services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${PSQL_USER:-test}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD:-test}

    volumes:
      - postgresql-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    restart: unless-stopped

    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-test}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-test}

    volumes:
      - mongodb-data:/data/db
    
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    restart: unless-stopped

    volumes:
      - redis-data:/data

    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    restart: unless-stopped

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    environment:
      bootstrap.memory_lock: true
      node.name: elastic-node

      cluster.name: elastic-cluster
      cluster.initial_master_nodes: elastic-node

      http.host: 0.0.0.0
      transport.host: 0.0.0.0

      xpack.security.enabled: false
      xpack.security.enrollment.enabled: true

      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-test}

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.2
    depends_on:
      - elasticsearch
    
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      TELEMETRY_ENABLED: false

    ports:
      - 5601:5601

    networks:
      - elk

volumes:
  postgresql-data:
  mongodb-data:
  redis-data:
  elasticsearch-data:

networks:
  elk: